# ==========================================
# Pipeline Configuration: config.yaml
# ==========================================

data:
  base_path: "data/processed/dalia"
  # Uncomment to use the wesad dataset instead
  # base_path: "data/processed/wesad"

inference:
  patient_id: "S1"
  bvp_freq: 64
  acc_freq: 32

params:
  seconds_per_window: 8
  step_size: 2
