"""
Clinical Report Generator Module.

This module provides the :class:`ClinicalReportGenerator` class, which serves
as the final delivery layer (Stage 3) of the clinical insights architecture.
It is responsible for taking the structured text and contextual insights
generated by the LLM and formatting them into actionable, human-readable
reports (e.g., PDFs, UI dashboards, or formatted text summaries) for
end-users or medical professionals.
"""
import textwrap
from datetime import datetime
import os

from src.schemas import ClinicalReportOutput


class ClinicalReportGeneratorPipeline:
    """
    Handles the formatting and export of final clinical insights.

    This class decouples the presentation layer from the analytical layers.
    By isolating report generation, the system can easily support multiple
    output formats (e.g., Markdown, HTML, PDF) without modifying the
    underlying LLM or signal processing pipelines.

    :ivar config: The global configuration dictionary containing export
                  preferences, output directories, and template paths.
    :vartype config: dict
    :ivar output_dir: The directory where the generated reports will be saved.
    :vartype output_dir: str
    """

    def __init__(self, config: dict):
        """
        Initializes the report generator with formatting and export configurations.

        :param config: A dictionary containing UI, template, or export settings
                       (e.g., 'report_output_path').
        """
        self.config = config

        # Example of safely pulling the output directory from the config,
        # with a fallback default just in case it isn't specified.
        self.output_dir = self.config.get('report_output_dir', 'reports/')

        # Ensure the output directory exists
        os.makedirs(self.output_dir, exist_ok=True)

    def _format_file(self, clinical_report: ClinicalReportOutput) -> str:
        """
        Formats the structured Pydantic report into a human-readable Markdown document.

        This internal helper method extracts the validated clinical insights,
        evaluates the triage level to determine the appropriate visual banner,
        and structures the data into a standardized Markdown template suitable
        for clinical review or downstream PDF conversion.

        :param clinical_report: The validated Pydantic object containing the
                                        LLM-generated telemetry insights.
        :type clinical_report: ClinicalReport

        :return: The fully rendered Markdown document as a raw string, ready
                         to be written to disk.
        :rtype: str
        """
        # 1. Triage Banner (Using headers for size)
        if clinical_report.requires_attention:
            status_banner = "### 🛑 URGENT: REQUIRES IMMEDIATE ATTENTION 🛑"
        else:
            status_banner = "### ✅ STATUS: NORMAL BASELINE"

        # 2. Format EWS HR Score with color coding
        ews_score = clinical_report.ews_hr_score
        if ews_score == 0:
            ews_label = "✅ **0 (Normal)** - HR in safe zone"
        elif ews_score == 1:
            ews_label = "⚠️ **1 (Borderline)** - HR slightly elevated/low"
        elif ews_score == 2:
            ews_label = "🟠 **2 (Elevated)** - HR moderately abnormal"
        else:  # ews_score == 3
            ews_label = "🛑 **3 (Critical)** - HR critically abnormal"

        # 3. Format Anomalies as HTML List for tighter spacing
        if clinical_report.anomalies_detected:
            anomalies_html = "\n".join(
                f"<li><b>{a}</b></li>" for a in clinical_report.anomalies_detected
            )
        else:
            anomalies_html = "<li><i>No anomalies detected.</i></li>"

        # 4. Generate timestamp
        timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

        # 5. Construct the HTML-Enhanced Markdown document
        # We use a Markdown Table to force the text into constrained columns
        md_content = textwrap.dedent(f"""\
# 📊 Clinical Telemetry Report
> **Generated:** `{timestamp}` &nbsp;&nbsp;|&nbsp;&nbsp; **Observation Window:** `120s`
{status_banner}

<hr>

### 🩺 Primary Observation
**{clinical_report.primary_observation}**

<br>

### 📈 System Metrics
| Category | Clinical Analysis |
| :--- | :--- |
| **🚨 EWS HR Score** | {ews_label} |
| **❤️ Cardiovascular** | {clinical_report.cardiovascular_state} |
| **🧠 Autonomic Tone** | {clinical_report.autonomic_tone} |
| **🏃 Movement Context** | {clinical_report.movement_context} |

<br>

### ⚠️ Detected Anomalies
<ul>
{anomalies_html}
</ul>

### 📋 Recommended Action Plan
> {clinical_report.recommended_system_action}

<br>
<br>

<details>
<summary><b>⚙️ Technical & Alignment Notes (Click to Expand)</b></summary>
<p><i>{clinical_report.technical_notes}</i></p>
</details>
""")

        return md_content

    def run(self, clinical_report: ClinicalReportOutput) -> str:
        """
        Takes the structured AI output and formats it into a human-readable document.

        :param clinical_report: The validated Pydantic object containing the LLM insights.
        :return: The absolute or relative file path to the generated report.
        """

        timestamp = datetime.now().strftime("%Y-%m-%d-%H-%M-%S")
        filename = f"clinical_report_{timestamp}.md"
        filepath = os.path.join(self.output_dir, filename)

        content = self._format_file(clinical_report)

        with open(filepath, "w", encoding="utf-8") as f:
            f.write(content)

        print(f"Report saved to {filepath}")
        return filepath
