"""
LLM Insights Pipeline Module.

This module provides the :class:`LLMInsightsPipeline` class, which serves as
the cognitive engine of the clinical insights architecture (Stages 3 & 4).
It is responsible for taking raw, continuous physiological predictions (like
heart rate arrays), aggregating them into meaningful clinical contexts, and
interfacing with Large Language Models (LLMs) to generate human-readable
clinical text.
"""
import json

from langchain_core.prompts import ChatPromptTemplate
from langsmith import traceable
from pydantic import BaseModel

from src.models.llm_creation import choice_model
from src.prompts import CLINICAL_SYSTEM_PROMPT
from src.schemas import ClinicalReportOutput


class LLMInsightsPipeline:
    """
    Executes the LLM explanation workflow.

    This pipeline handles the transformation of structured numerical arrays
    into actionable clinical insights. It manages the prompt engineering,
    context aggregation, and API interactions required to produce the final
    clinical text.

    :ivar config: The global configuration dictionary containing LLM parameters,
                      prompt templates, and API settings.
    :vartype config: dict
    """

    def __init__(self, config: dict):
        """
        Initializes the insights pipeline with the necessary configuration.
        Compiles the LangChain execution graph (Prompt -> Model -> String Parser)
        once upon initialization for high-speed inference.

        :param config: A dictionary containing the settings required for
                       aggregation and LLM interaction.
        """
        self.config = config
        llm_param_list = self.config.get("llm", {})
        raw_model = self._model_creation(
            provider=llm_param_list.get("provider", "google"),
            model_name=llm_param_list.get("model_name", "gemini-3.1-flash-lite"),
            temperature=llm_param_list.get("temperature", 0.1)
        )
        self.model = raw_model.with_structured_output(ClinicalReportOutput)

        self.chat_template = ChatPromptTemplate.from_messages([
            ("system", CLINICAL_SYSTEM_PROMPT),
            ("user", (
                "### INPUT: 120-SECOND TELEMETRY PAYLOAD\n"
                "```json\n{clinical_data}\n```\n\n"
                "Analyze the payload above according to the clinical directives "
                "and generate the structured observational report."
            ))
        ])

        self.chain = self.chat_template | self.model

    def _model_creation(self, provider: str, model_name: str, temperature: float):
        """
        Helper method to dynamically instantiate the chat model
        based on the global configuration parameters.

        :param provider: The provider name of the model
        :param model_name: The name of the model
        :param temperature: The temperature of the model

        :return: A configured instance of the provided model
        """

        return choice_model(
            model_provider=provider,
            model_name=model_name,
            temperature=temperature
        )

    @traceable
    def _pipeline(self, payload: dict) -> BaseModel:
        """
        Internal method to execute the LangChain pipeline with LangSmith tracing.

        :param payload: A dictionary containing the aggregated clinical telemetry data.
        :return: A Markdown-formatted string containing the clinical report.
        """
        formatted_payload = json.dumps(payload, indent=2)

        final_report = self.chain.invoke({
            "clinical_data": formatted_payload
        })

        return final_report


    def run(self, payload: dict) -> ClinicalReportOutput:
        """
        Executes the LLM insights generation process.

        Takes the structured numerical arrays from the ClinicalAggregator and
        triggers the internal cognitive pipeline to generate human-readable
        clinical text.

        :param payload: A dictionary containing the aggregated data.
        :return: The final clinical report generated by the LLM.
        """
        print("Generating LLM clinical response...")

        return self._pipeline(payload=payload)
